/** @format */

import { Box, useTheme } from "@mui/material";
import Header from "../../components/Header";
import Accordion from "@mui/material/Accordion";
import AccordionSummary from "@mui/material/AccordionSummary";
import AccordionDetails from "@mui/material/AccordionDetails";
import Typography from "@mui/material/Typography";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import { tokens } from "../../theme";

const FAQ = () => {
  const theme = useTheme();
  const colors = tokens(theme.palette.mode);
  return (
    <Box m="20px">
      <Header title="FAQ" subtitle="Pharmacy Manager Dashboard" />

      <Accordion defaultExpanded>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography color={colors.greenAccent[500]} variant="h5">
            Q: What is the Pharmacy Manager Dashboard port?
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            A: The Pharmacy Manager Dashboard port is a web-based platform that
            allows pharmacists and pharmacy managers to manage their pharmacies
            more efficiently. It provides a comprehensive view of the pharmacy's
            operations, including total prescriptions filled within a store,
            total prescriptions sold, total patients, revenue generated, recent
            transactions, and more.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion defaultExpanded>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography color={colors.greenAccent[500]} variant="h5">
            Q: What kind of information can I see on the Pharmacy Manager
            Dashboard?
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            A: The Pharmacy Manager Dashboard provides a wealth of information
            about your pharmacy, including the total number of prescriptions
            filled, the total number of prescriptions sold, the total number of
            patients served, and the revenue generated by your pharmacy. You can
            also view recent transactions and get an AI prediction for future
            sales.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion defaultExpanded>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography color={colors.greenAccent[500]} variant="h5">
            Q: How does the AI prediction work?
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            A: The AI prediction is based on data analytics and machine learning
            algorithms. We calculate the total quantity and number of aspirin
            sold for each medication in the response data, and then calculate
            the sale prediction for each medication by dividing the total
            quantity by the number of aspirin sold. Finally, it returns the name
            of the medication with the highest sale prediction.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion defaultExpanded>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography color={colors.greenAccent[500]} variant="h5">
            Q: What is Patient 360view?
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            A: Patient 360view is a tool that allows pharmacists and pharmacy
            managers to view a patient's complete medical history and track
            their medication history, allergies, and other relevant health
            information.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion defaultExpanded>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography color={colors.greenAccent[500]} variant="h5">
            Q: What is the AI virtual assistant?
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            A: The AI virtual assistant is an AI-powered tool that provides
            patients with a virtual assistant to assist them with their
            health-related queries. It can provide information about
            medications, side effects, interactions, and more.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion defaultExpanded>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography color={colors.greenAccent[500]} variant="h5">
            Q: What is Lab 360?
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            A: Lab 360 is a tool that allows pharmacists and pharmacy managers
            to view a patient's lab results and track their health metrics over
            time. It can help pharmacists and pharmacy managers to identify
            potential health issues and provide personalized recommendations.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion defaultExpanded>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography color={colors.greenAccent[500]} variant="h5">
            Q: What is Medication Compound View?
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            A: Medication Compound View is a tool that allows pharmacists and
            pharmacy managers to track the production and distribution of
            compounded medications. It can help to ensure that patients receive
            the correct dosage and that medications are prepared safely and
            accurately.
          </Typography>
        </AccordionDetails>
      </Accordion>
    </Box>
  );
};

export default FAQ;
