# @format

version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: rxcare
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: ./app
    command: uvicorn care:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app/.:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  aiml:
    build: ./aiml
    command: uvicorn aiml:app --host 0.0.0.0 --port 2323
    volumes:
      - ./aiml.:/app
    ports:
      - "2323:2323"
    depends_on:
      - app
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://app:8000
    depends_on:
      - app
    volumes:
      - ./web/.:/app
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
  grafana:
    image: "grafana/grafana"
    ports:
      - "2000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana/
  linux-health:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9100:9100"
