# @format

global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["app:8000"]
  - job_name: "db"
    static_configs:
      - targets: ["db:5432"]
  - job_name: "linux-health"
    static_configs:
      - targets: ["linux-health:9100"]  
